In [1]:
import Liblinks.utis as f_s
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import *
from PIL import Image
from torchvision import transforms
import torchvision.transforms.functional as tf
import os
from torch.optim import RMSprop
from torchvision.utils import make_grid
from pylab import plt
from Liblinks.sn_lib import *


In [2]:
snconv=SNConv2d(3,2,1,bias=False)

In [3]:
print(snconv.weight)

Parameter containing:
tensor([[[[ 0.0746]],

         [[ 0.2081]],

         [[ 0.2436]]],


        [[[ 0.5353]],

         [[-0.3287]],

         [[ 0.1643]]]], requires_grad=True)


In [4]:
sn_linear=SNLinear(2,3,bias=False)

In [5]:
input = torch.randn(10, 2)
out=sn_linear(input)

0.8340652
tensor([[-0.3575, -0.4913],
        [-0.2576,  0.5294],
        [ 0.0027,  0.7981]], grad_fn=<DivBackward0>)


In [6]:
print(out)

tensor([[-0.0448,  0.5104,  0.4883],
        [-0.5447,  0.8556,  1.1263],
        [-0.8277,  0.1525,  0.6796],
        [-0.5501, -0.3576,  0.0390],
        [ 0.2476, -0.5684, -0.6734],
        [ 0.9733, -1.1361, -1.6595],
        [ 0.2841,  0.3491,  0.1278],
        [-0.4692,  0.4968,  0.7543],
        [-0.0404, -0.2936, -0.2376],
        [ 0.0828,  0.4409,  0.3423]], grad_fn=<MmBackward>)


In [7]:
print(sn_linear.weight)

Parameter containing:
tensor([[-0.2982, -0.4098],
        [-0.2148,  0.4416],
        [ 0.0023,  0.6657]], requires_grad=True)


In [8]:
print(input)

tensor([[-0.7189,  0.6143],
        [-0.4179,  1.4126],
        [ 1.1502,  0.8477],
        [ 1.4783,  0.0438],
        [ 0.4693, -0.8453],
        [ 0.1358, -2.0798],
        [-1.0193,  0.1636],
        [ 0.0136,  0.9450],
        [ 0.5244, -0.2995],
        [-0.8247,  0.4316]])


In [10]:
d2_input=torch.randn(10,3,2,2)

In [11]:
out_2d=snconv(d2_input)

In [12]:
print(out_2d)

tensor([[[[ 0.1584,  0.2444],
          [-0.5218,  0.0029]],

         [[-0.5211, -0.5437],
          [-1.3526,  1.1424]]],


        [[[-1.2919, -0.4335],
          [ 1.0042, -0.2169]],

         [[-0.0604,  0.1357],
          [ 0.7636, -0.7842]]],


        [[[ 0.1522,  1.0799],
          [ 0.6534,  0.0932]],

         [[-0.6756,  1.1811],
          [-0.1546, -0.7726]]],


        [[[ 0.2342,  0.4085],
          [ 0.1331,  0.3393]],

         [[-0.7656, -1.4160],
          [-0.2332, -0.3203]]],


        [[[ 0.0754,  0.6335],
          [ 0.4783, -0.2867]],

         [[-0.6595, -1.4869],
          [ 0.2975, -0.1455]]],


        [[[ 0.3314,  0.3597],
          [ 0.2064, -0.9776]],

         [[-0.5822, -1.2639],
          [-0.8383, -1.4447]]],


        [[[ 0.2672, -0.3126],
          [ 0.5362, -0.3976]],

         [[ 0.1151, -0.4971],
          [-0.6086,  0.4936]]],


        [[[ 0.2908,  0.1725],
          [ 0.0395, -0.0875]],

         [[-0.4418,  0.0146],
          [ 1.2311, -0.847

In [3]:
emb=SNEmbedCLS(10,4)

In [5]:
input=torch.LongTensor([[4,0,2,4]])
print(emb(input))

tensor([[[-0.1489,  0.2807, -0.0212,  0.2507],
         [-0.2143,  0.0346, -0.0116,  0.1392],
         [ 0.4397, -0.1944,  0.0111, -0.0149],
         [-0.1489,  0.2807, -0.0212,  0.2507]]], grad_fn=<EmbeddingBackward>)


In [5]:
a=torch.randn(3,1,5)
b=torch.randn(3,5,1)

In [6]:
print(a,b)

tensor([[[[ 0.1685, -1.4469, -0.5227,  1.6810, -0.6019]]],


        [[[ 0.2006,  0.4981,  0.8309,  0.8294,  0.6330]]],


        [[[ 0.4897, -0.1448,  0.2728, -0.2101, -1.3357]]]]) tensor([[[[ 0.2880],
          [ 0.5534],
          [ 0.5448],
          [ 0.0127],
          [ 0.3752]]],


        [[[-0.7815],
          [-2.1474],
          [-1.6255],
          [ 1.3705],
          [-0.9349]]],


        [[[-0.6163],
          [-0.1407],
          [ 0.4289],
          [-1.4995],
          [ 0.6002]]]])


In [12]:
anb=torch.matmul(a,b)

In [13]:
print(anb)

tensor([[[[-1.2415]]],


        [[[-2.0322]]],


        [[[-0.6510]]]])


In [18]:
b_1=b.view(3,1,1,5)
print(b_1)

tensor([[[[ 0.2880,  0.5534,  0.5448,  0.0127,  0.3752]]],


        [[[-0.7815, -2.1474, -1.6255,  1.3705, -0.9349]]],


        [[[-0.6163, -0.1407,  0.4289, -1.4995,  0.6002]]]])


In [47]:
anb_1=torch.mul(a,b_1)

RuntimeError: Expected tensor to have size 5 at dimension 1, but got size 1 for argument #2 'batch2' (while checking arguments for bmm)

In [20]:
print(anb_1)

tensor([[[[ 0.0485, -0.8008, -0.2847,  0.0213, -0.2259]]],


        [[[-0.1567, -1.0697, -1.3506,  1.1367, -0.5918]]],


        [[[-0.3018,  0.0204,  0.1170,  0.3151, -0.8016]]]])


In [21]:
print(a.size())

torch.Size([3, 1, 1, 5])


In [22]:
b_2=b.view(a.size())#用view来对齐某个张量的size

In [23]:
print(b_2)

tensor([[[[ 0.2880,  0.5534,  0.5448,  0.0127,  0.3752]]],


        [[[-0.7815, -2.1474, -1.6255,  1.3705, -0.9349]]],


        [[[-0.6163, -0.1407,  0.4289, -1.4995,  0.6002]]]])


In [24]:
print(a.size(0))

3


In [33]:
cv1=nn.Conv2d(3,4,1)
cl=nn.Linear(4,1)
avg=nn.AdaptiveAvgPool2d(1)

In [36]:
x=torch.randn(2,3,4,4)
print(x)

tensor([[[[ 0.4649,  0.9935,  1.0971,  1.0195],
          [-1.5548,  0.3147,  1.5516,  0.0909],
          [-1.1605, -1.1982, -0.7820,  0.3801],
          [-1.1502, -0.4309, -1.5485, -0.7550]],

         [[-1.9007,  0.0426, -0.8200,  0.8193],
          [-0.4436,  1.3320,  1.3528, -0.2758],
          [-0.6366,  0.6098, -2.0121,  0.5197],
          [-1.9599, -0.1328,  0.0997, -0.1471]],

         [[-0.2544, -0.3944,  0.1246, -1.7999],
          [-0.5695,  0.8072,  0.6319, -0.7992],
          [-1.0589,  0.4223,  0.9074, -0.3841],
          [-0.4180, -0.3334,  1.0198,  0.6387]]],


        [[[ 0.0841, -0.2727,  0.3706,  0.6539],
          [-0.4307,  0.6408, -1.6681, -1.4445],
          [ 1.0051, -1.7785,  0.6686,  2.3857],
          [-0.5427,  2.1993,  1.5766,  2.0408]],

         [[ 0.5709, -0.4789, -0.0587, -0.4162],
          [-2.9936,  0.7855, -1.6550,  1.4528],
          [-1.3533, -0.3847, -0.1312,  0.9748],
          [-0.2615, -0.1722, -1.9861, -1.0599]],

         [[-0.0103, -0.3185,

In [46]:
out=cv1(x)
#print(out.view(out.size(0),out.size(1),-1))#size(0)都是指batch的个数
out=avg(out)
print(out.size(0))
out_1=out.view(out.size(0),-1)
print(out_1)

tensor([[[ 8.0537e-01, -1.6401e-01, -1.2216e-02, -1.0195e-01,  1.2429e+00,
          -6.8503e-01, -1.2129e+00,  4.8447e-01,  1.2704e+00,  3.9682e-01,
           1.1070e+00, -7.3396e-02,  1.6134e+00,  5.4152e-01,  5.9676e-01,
           4.3310e-01],
         [ 1.0693e+00,  4.4111e-01,  1.0021e+00, -3.9934e-01, -2.0906e-01,
           2.2775e-01,  5.2135e-01,  1.3024e-01, -2.1183e-01, -1.0620e-01,
           1.1970e+00,  8.1814e-02,  5.4271e-01,  1.0427e-01,  2.1713e-01,
           3.9708e-01],
         [ 1.0073e+00,  5.0090e-02,  7.6125e-01, -1.1211e+00, -4.8744e-04,
           8.6731e-02,  6.2871e-02, -9.6092e-02, -1.6334e-01,  9.9183e-02,
           1.6401e+00, -2.1130e-01,  8.2797e-01,  6.7810e-02,  6.5793e-01,
           6.1052e-01],
         [-2.6157e-01, -1.0406e-01, -2.5452e-01,  1.9978e-01, -1.1459e-01,
          -2.3495e-01, -1.9771e-01, -5.6251e-02, -3.8540e-02, -2.2006e-01,
          -4.8150e-01, -7.6074e-02, -2.4210e-01, -1.3191e-01, -3.6254e-01,
          -3.0803e-01]],

  

In [52]:
out_linear=cl(out_1)

In [39]:
print(out_linear)

tensor([[-0.2645],
        [-0.4825]], grad_fn=<AddmmBackward>)


In [51]:
print(out_1.view(-1,out_1.size(0)))

tensor([[ 0.3901,  0.3128],
        [ 0.2675, -0.1803],
        [ 0.2186,  0.5898],
        [ 0.4663, -0.2113]], grad_fn=<ViewBackward>)


In [49]:
out_2=torch.matmul(out_1,out_1.view(-1,out_1.size(0)))

In [50]:
print(out_2)

tensor([[0.2103, 0.2615],
        [0.2464, 0.2817]], grad_fn=<MmBackward>)


In [53]:
embed=SNEmbedCLS(3,4)

In [54]:
label=torch.LongTensor([1,2])

In [55]:
print(label)

tensor([1, 2])


In [56]:
e_m=embed(label)
print(e_m)

tensor([[-0.1557, -0.3013,  0.6754, -0.0287],
        [ 0.0333,  0.1653, -0.5748,  0.0145]], grad_fn=<EmbeddingBackward>)


In [59]:
y=torch.mul(e_m,out_1)
print(y)

tensor([[-0.0608, -0.0943,  0.1806,  0.0052],
        [ 0.0073,  0.0975, -0.2680, -0.0031]], grad_fn=<MulBackward0>)


In [61]:
y_1=y.sum(dim=1,keepdim=True)
print(y_1)

tensor([[ 0.0308],
        [-0.1663]], grad_fn=<SumBackward1>)


In [62]:
print(out_linear+y_1)

tensor([[-0.2338],
        [-0.6488]], grad_fn=<AddBackward0>)
