In [1]:
import numpy as np
import torch
import torch.nn as nn
import scipy

In [2]:
#读数据
data=np.loadtxt("irisdatamodified.data",delimiter=',')
train_data1=data[0:40,0:4] #第一类
train_data2=data[50:90,0:4]#第二类
train_data3=data[100:140,0:4]#3
train_label1=data[0:40,-1:]
train_label2=data[50:90,-1:]
train_label3=data[100:140,-1:]
train_X=np.vstack([train_data1,train_data2,train_data3])
train_Y=np.vstack([train_label1,train_label2,train_label3])
print(train_X,train_Y)
test_data1=data[40:50,0:4]
test_data2=data[90:100,:-1]
test_data3=data[140:150,:-1]
test_label1=data[40:50,-1:]
test_label2=data[90:100,-1:]
test_label3=data[100:140,-1:]
test_X=np.vstack([test_data1,test_data2,test_data3])
test_Y=np.vstack([test_label1,test_label2,test_label3])
print(test_X,test_Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.

In [3]:
inv_se=np.linalg.inv(np.dot(train_X.T,train_X))
X_y=np.dot(train_X.T,train_Y)#np.dot(test_X,np.dot(inv_se,np.dot(train_X.T,train_Y)))
w=np.dot(inv_se,X_y)
print(np.dot(test_X,w))
print(np.dot(test_X,np.dot(inv_se,np.dot(train_X.T,train_Y))))

[[0.9590219 ]
 [0.81943189]
 [0.86825941]
 [1.1748013 ]
 [1.19589017]
 [0.92715045]
 [1.02592256]
 [0.89860702]
 [0.99329016]
 [0.91782352]
 [2.09470972]
 [2.294264  ]
 [1.99660037]
 [1.67299038]
 [2.10115923]
 [2.08971584]
 [2.12477698]
 [2.16147399]
 [1.66407585]
 [2.08791165]
 [3.03697808]
 [2.86482581]
 [2.61529501]
 [3.08237746]
 [3.13040583]
 [2.87595692]
 [2.57826137]
 [2.73428865]
 [2.96060653]
 [2.60385161]]
[[0.9590219 ]
 [0.81943189]
 [0.86825941]
 [1.1748013 ]
 [1.19589017]
 [0.92715045]
 [1.02592256]
 [0.89860702]
 [0.99329016]
 [0.91782352]
 [2.09470972]
 [2.294264  ]
 [1.99660037]
 [1.67299038]
 [2.10115923]
 [2.08971584]
 [2.12477698]
 [2.16147399]
 [1.66407585]
 [2.08791165]
 [3.03697808]
 [2.86482581]
 [2.61529501]
 [3.08237746]
 [3.13040583]
 [2.87595692]
 [2.57826137]
 [2.73428865]
 [2.96060653]
 [2.60385161]]
